import Foundation

/// A titled block of lines in a shareable trip brief.
public struct TripBriefSection: Sendable, Equatable {
    /// Optional section heading (e.g. Stops, Predictive telemetry).
    public let title: String?
    /// Body lines for the section.
    public let lines: [String]

    /// Creates a trip brief section.
    public init(title: String? = nil, lines: [String]) {
        self.title = title
        self.lines = lines
    }
}

/// Formats a predictive trip brief as plain text for Messages, email, or clipboard.
public enum TripBriefFormatter {
    /// Builds structured sections from the unified context.
    public static func sections(from context: TripBriefContext) -> [TripBriefSection] {
        var result: [TripBriefSection] = []

        var headerLines: [String] = []
        if let vehicleLabel = context.vehicleLabel, !vehicleLabel.isEmpty {
            headerLines.append("Vehicle: \(vehicleLabel)")
        }
        if let tripStatus = context.tripStatus, !tripStatus.isEmpty {
            headerLines.append("Trip status: \(tripStatus)")
        }
        result.append(TripBriefSection(title: "RouteFinder Trip Brief", lines: headerLines))

        if !context.stops.isEmpty {
            let stopLines = context.stops.enumerated().map { index, stop in
                let roleSuffix = stop.role.map { " (\($0))" } ?? ""
                return "\(index + 1). \(stop.label)\(roleSuffix)"
            }
            result.append(TripBriefSection(title: "Stops", lines: stopLines))
        }

        if !context.companyBreaks.isEmpty {
            let breakLines = context.companyBreaks.map { allocation in
                let label = allocation.label ?? "Break"
                let durationMinutes = Int(allocation.durationSeconds / 60)
                let opens = allocation.window.start.formatted(date: .abbreviated, time: .shortened)
                let closes = allocation.window.end.formatted(date: .omitted, time: .shortened)
                return "\(label): \(opens) – \(closes), \(durationMinutes) min"
            }
            result.append(TripBriefSection(
                title: "Company break windows (planning aid — not legal tacho)",
                lines: breakLines
            ))
        }

        if let report = context.predictiveReport {
            result.append(telemetrySection(from: report))
        } else if let physicsETA = context.physicsETASeconds {
            result.append(TripBriefSection(
                lines: ["Physics ETA: \(formatDuration(physicsETA))"]
            ))
        }

        if let hosForecast = context.hosForecast {
            var hosLines = [hosForecast.summary]
            if !hosForecast.summary.contains(HosRestInsertionResult.legalDisclaimer) {
                hosLines.append(HosRestInsertionResult.legalDisclaimer)
            }
            result.append(TripBriefSection(title: "Hours of service (advisory)", lines: hosLines))
        }

        if let layby = context.laybyAdvisory {
            result.append(laybySection(from: layby))
        }

        result.append(TripBriefSection(
            lines: ["Generated by RouteFinder predictive telematics."]
        ))

        return result
    }

    /// Builds a plain-text trip brief from the unified context.
    public static func plainText(from context: TripBriefContext) -> String {
        plainText(from: sections(from: context))
    }

    /// Builds a plain-text trip brief from structured sections.
    public static func plainText(from sections: [TripBriefSection]) -> String {
        var lines: [String] = []
        for (index, section) in sections.enumerated() {
            if index == 0 {
                if let title = section.title {
                    lines.append(title)
                }
                lines.append("─────────────────────")
                lines.append(contentsOf: section.lines)
            } else if index == sections.count - 1 {
                lines.append(contentsOf: section.lines)
            } else if !section.lines.isEmpty || section.title != nil {
                lines.append("─────────────────────")
                if let title = section.title {
                    lines.append(title)
                }
                lines.append(contentsOf: section.lines)
            }
        }
        return lines.joined(separator: "\n")
    }

    /// Builds a plain-text trip brief from telemetry only (backward compatible).
    public static func plainText(
        from report: PredictiveTelemetryReport,
        hosForecast: HosRestInsertionResult? = nil
    ) -> String {
        plainText(from: TripBriefContext(predictiveReport: report, hosForecast: hosForecast))
    }

    private static func telemetrySection(from report: PredictiveTelemetryReport) -> TripBriefSection {
        let staticETA = formatDuration(report.staticWebETASeconds)
        let kineticETA = formatDuration(report.kineticPhysicsETASeconds)
        let delta = report.kineticPhysicsETASeconds - report.staticWebETASeconds
        let deltaLabel = delta >= 0
            ? "+\(formatDuration(delta)) vs web ETA"
            : "−\(formatDuration(abs(delta))) vs web ETA"

        var lines = [
            "Web routing ETA: \(staticETA)",
            "Physics kinetic ETA: \(kineticETA) (\(deltaLabel))",
            String(format: "Brake/Kinetic efficiency: %.0f / 100", report.brakeWearKineticEfficiencyIndex),
            "Hard decelerations: \(report.hardDecelEventCount)",
            "Brake fade risks: \(report.brakeFadeRiskEventCount)",
            "Lateral G violations: \(report.lateralGViolationCount)",
            "Tire slip events: \(report.tireSlipEventCount)",
        ]

        if let fade = report.brakeFadeRiskState {
            lines.append("Peak brake fade: \(String(describing: fade))")
        }

        if report.estimatedPremiumSavingsGBP > 0 {
            lines.append("Est. premium impact: £\(report.estimatedPremiumSavingsGBP)")
        }

        return TripBriefSection(title: "Predictive telemetry", lines: lines)
    }

    private static func laybySection(from advisory: LaybyAdvisory) -> TripBriefSection {
        var lines = [advisory.stop.label]
        if let eta = advisory.estimatedArrivalSeconds {
            lines.append("ETA ~\(formatDuration(eta)) · occupancy: \(advisory.occupancyPrior.displayLabel)")
        } else {
            lines.append("Occupancy prior: \(advisory.occupancyPrior.displayLabel)")
        }
        if let opens = advisory.breakWindowOpensAt {
            lines.append("Break window opens \(opens.formatted(date: .omitted, time: .shortened))")
        }
        if advisory.isAdvisory {
            lines.append("Planning aid only — digital tachograph remains the legal record.")
        }
        return TripBriefSection(
            title: "Predicted layby (advisory — not legal tacho)",
            lines: lines
        )
    }

    private static func formatDuration(_ seconds: TimeInterval) -> String {
        let total = max(0, Int(seconds.rounded()))
        let hours = total / 3600
        let minutes = (total % 3600) / 60
        if hours > 0 {
            return "\(hours)h \(minutes)m"
        }
        return "\(minutes) min"
    }
}
