import Foundation

/// Formats a predictive trip brief as plain text for Messages, email, or clipboard.
public enum TripBriefFormatter {
    /// Builds a plain-text trip brief from the unified context.
    public static func plainText(from context: TripBriefContext) -> String {
        var lines = ["RouteFinder Trip Brief", "─────────────────────"]

        if let vehicleLabel = context.vehicleLabel, !vehicleLabel.isEmpty {
            lines.append("Vehicle: \(vehicleLabel)")
        }
        if let tripStatus = context.tripStatus, !tripStatus.isEmpty {
            lines.append("Trip status: \(tripStatus)")
        }

        if !context.stops.isEmpty {
            lines.append("─────────────────────")
            lines.append("Stops")
            for (index, stop) in context.stops.enumerated() {
                let roleSuffix = stop.role.map { " (\($0))" } ?? ""
                lines.append("\(index + 1). \(stop.label)\(roleSuffix)")
            }
        }

        if !context.companyBreaks.isEmpty {
            lines.append("─────────────────────")
            lines.append("Company break windows (planning aid — not legal tacho)")
            for allocation in context.companyBreaks {
                let label = allocation.label ?? "Break"
                let durationMinutes = Int(allocation.durationSeconds / 60)
                let opens = allocation.window.start.formatted(date: .abbreviated, time: .shortened)
                let closes = allocation.window.end.formatted(date: .omitted, time: .shortened)
                lines.append("\(label): \(opens) – \(closes), \(durationMinutes) min")
            }
        }

        if let report = context.predictiveReport {
            lines.append(contentsOf: telemetryLines(from: report))
        } else if let physicsETA = context.physicsETASeconds {
            lines.append("─────────────────────")
            lines.append("Physics ETA: \(formatDuration(physicsETA))")
        }

        if let hosForecast = context.hosForecast {
            lines.append("─────────────────────")
            lines.append("Hours of service (advisory)")
            lines.append(hosForecast.summary)
            if !hosForecast.summary.contains(HosRestInsertionResult.legalDisclaimer) {
                lines.append(HosRestInsertionResult.legalDisclaimer)
            }
        }

        if let layby = context.laybyAdvisory {
            lines.append(contentsOf: laybyLines(from: layby))
        }

        lines.append("Generated by RouteFinder predictive telematics.")
        return lines.joined(separator: "\n")
    }

    /// Builds a plain-text trip brief from telemetry only (backward compatible).
    public static func plainText(
        from report: PredictiveTelemetryReport,
        hosForecast: HosRestInsertionResult? = nil
    ) -> String {
        plainText(from: TripBriefContext(predictiveReport: report, hosForecast: hosForecast))
    }

    private static func telemetryLines(from report: PredictiveTelemetryReport) -> [String] {
        let staticETA = formatDuration(report.staticWebETASeconds)
        let kineticETA = formatDuration(report.kineticPhysicsETASeconds)
        let delta = report.kineticPhysicsETASeconds - report.staticWebETASeconds
        let deltaLabel = delta >= 0
            ? "+\(formatDuration(delta)) vs web ETA"
            : "−\(formatDuration(abs(delta))) vs web ETA"

        var lines = [
            "─────────────────────",
            "Predictive telemetry",
            "Web routing ETA: \(staticETA)",
            "Physics kinetic ETA: \(kineticETA) (\(deltaLabel))",
            String(format: "Brake/Kinetic efficiency: %.0f / 100", report.brakeWearKineticEfficiencyIndex),
            "Hard decelerations: \(report.hardDecelEventCount)",
            "Brake fade risks: \(report.brakeFadeRiskEventCount)",
            "Lateral G violations: \(report.lateralGViolationCount)",
            "Tire slip events: \(report.tireSlipEventCount)",
        ]

        if let fade = report.brakeFadeRiskState {
            lines.append("Peak brake fade: \(String(describing: fade))")
        }

        if report.estimatedPremiumSavingsGBP > 0 {
            lines.append("Est. premium impact: £\(report.estimatedPremiumSavingsGBP)")
        }

        return lines
    }

    private static func laybyLines(from advisory: LaybyAdvisory) -> [String] {
        var lines = [
            "─────────────────────",
            "Predicted layby (advisory — not legal tacho)",
            advisory.stop.label,
        ]
        if let eta = advisory.estimatedArrivalSeconds {
            lines.append("ETA ~\(formatDuration(eta)) · occupancy: \(advisory.occupancyPrior.displayLabel)")
        } else {
            lines.append("Occupancy prior: \(advisory.occupancyPrior.displayLabel)")
        }
        if let opens = advisory.breakWindowOpensAt {
            lines.append("Break window opens \(opens.formatted(date: .omitted, time: .shortened))")
        }
        if advisory.isAdvisory {
            lines.append("Planning aid only — digital tachograph remains the legal record.")
        }
        return lines
    }

    private static func formatDuration(_ seconds: TimeInterval) -> String {
        let total = max(0, Int(seconds.rounded()))
        let hours = total / 3600
        let minutes = (total % 3600) / 60
        if hours > 0 {
            return "\(hours)h \(minutes)m"
        }
        return "\(minutes) min"
    }
}
