import Contracts
import Foundation

/// Headless route rehearsal that produces a full predictive telemetry report before departure.
public enum RouteRehearsalService {
    private static let physicsStepSeconds = 1.0 / 60.0
    private static let headlessSpeedMultiplier = 100.0
    private static let maxSteps = 2_000_000
    public static let defaultTimeoutSeconds: TimeInterval = 20

    /// Rehearses a configured route and returns the predictive telematics report.
    public static func rehearse(
        configuration: SimulationPhysicsConfiguration,
        tomTomAPIKey: String? = nil,
        timeoutSeconds: TimeInterval = defaultTimeoutSeconds
    ) async -> PredictiveTelemetryReport? {
        guard configuration.totalRouteLength > 0 else { return nil }

        let mailbox = SimulationStateMailbox()
        let actor = SimulationPhysicsActor(tomTomAPIKey: tomTomAPIKey, mailbox: mailbox)
        await actor.configure(configuration)
        await actor.start()

        let deadline = ContinuousClock.now + .seconds(timeoutSeconds)
        var steps = 0
        while steps < maxSteps {
            if Task.isCancelled { return nil }
            if ContinuousClock.now >= deadline { return nil }

            if let completion = await actor.step(
                fixedDeltaTime: physicsStepSeconds,
                simulationSpeedMultiplier: headlessSpeedMultiplier
            ) {
                return completion.telemetryReport
            }
            steps += 1
            if steps.isMultiple(of: 2_000) {
                await Task.yield()
            }
        }
        return nil
    }
}

/// Formats a predictive telemetry report as a shareable trip brief.
public enum TripBriefFormatter {
    /// Builds a plain-text trip brief suitable for Messages / email / clipboard.
<<<<<<< HEAD
    public static func plainText(
        from report: PredictiveTelemetryReport,
        hosForecast: HosRestInsertionResult? = nil
    ) -> String {
=======
    public static func plainText(from report: PredictiveTelemetryReport) -> String {
>>>>>>> 131ad0b45323f7aa6d871049cbbcf4238fd0ed3b
        let staticETA = formatDuration(report.staticWebETASeconds)
        let kineticETA = formatDuration(report.kineticPhysicsETASeconds)
        let delta = report.kineticPhysicsETASeconds - report.staticWebETASeconds
        let deltaLabel = delta >= 0
            ? "+\(formatDuration(delta)) vs web ETA"
            : "−\(formatDuration(abs(delta))) vs web ETA"

        var lines = [
            "RouteFinder Trip Brief",
            "─────────────────────",
            "Web routing ETA: \(staticETA)",
            "Physics kinetic ETA: \(kineticETA) (\(deltaLabel))",
            String(format: "Brake/Kinetic efficiency: %.0f / 100", report.brakeWearKineticEfficiencyIndex),
            "Hard decelerations: \(report.hardDecelEventCount)",
            "Brake fade risks: \(report.brakeFadeRiskEventCount)",
            "Lateral G violations: \(report.lateralGViolationCount)",
            "Tire slip events: \(report.tireSlipEventCount)",
        ]

        if let fade = report.brakeFadeRiskState {
            lines.append("Peak brake fade: \(String(describing: fade))")
        }

        if report.estimatedPremiumSavingsGBP > 0 {
            lines.append("Est. premium impact: £\(report.estimatedPremiumSavingsGBP)")
        }

<<<<<<< HEAD
        if let hosForecast {
            lines.append("─────────────────────")
            lines.append("Hours of service (advisory)")
            lines.append(hosForecast.summary)
            if !hosForecast.summary.contains(HosRestInsertionResult.legalDisclaimer) {
                lines.append(HosRestInsertionResult.legalDisclaimer)
            }
        }

=======
>>>>>>> 131ad0b45323f7aa6d871049cbbcf4238fd0ed3b
        lines.append("Generated by RouteFinder predictive telematics.")
        return lines.joined(separator: "\n")
    }

    private static func formatDuration(_ seconds: TimeInterval) -> String {
        let total = max(0, Int(seconds.rounded()))
        let hours = total / 3600
        let minutes = (total % 3600) / 60
        if hours > 0 {
            return "\(hours)h \(minutes)m"
        }
        return "\(minutes) min"
    }
}
